apiVersion: 1

datasources:
  - name: Retail Analytics PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: retail_analytics
    user: grafana_user
    secureJsonData:
      password: grafana_password_123
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
